Выполнила опцию 3.
OlenaIvchenko/absolute pull request #1
Opened 2022-11-04 11:12 UTC by OlenaIvchenko

оставила в footer hf,jne, потому что хочу доделать остальные две опции в header и main позже

2022-11-09 16:45 UTC, a1exalexander requested changes
Потрібно доробити!
<img width="678" alt="image" src="https://user-images.githubusercontent.com/40409129/200889251-4312204f-0603-4361-bcac-15fe684a3848.png">
Трішки відрізняються блоки

- іконки не векторні, якість через це погана дуже
- межстроковий інтервал не такий `line-height`
- падінги скрізь по `32px` потрібно, fа внузу `40px`

2022-11-09 19:44 UTC, OlenaIvchenko commented
Саша, привет! векторы перезагрузила, padding поменяла, а вот с line-height у меня в стилях стоит те же значения, что и в figma, не могу понять почему картинки откличаються в итоге. я поменяла на глаз это значение и получила, картинку нужную, но не могу понять, если задан line-height 14, почему у меня он выглядит по-другому.

2022-11-11 11:18 UTC, merged

2022-11-11 11:18 UTC, a1exalexander commented
Усе круто! Зараховано

2022-11-11 18:01 UTC, OlenaIvchenko commented
Ура! Дякую!